name: flutter_challenge_model
description: 'Proyecto de prueba para el challenge de flutter'
publish_to: 'https://aaronmg2000-portfolio.web.app/'
version: 1.0.0+1

environment:
    sdk: ^3.10.8

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    cupertino_icons: ^1.0.8
    json_annotation: ^4.9.0
    intl_utils: ^2.8.13
    flutter_riverpod: ^3.1.0
    dartz: ^0.10.1
    dio: ^5.9.1
    shared_preferences: ^2.5.4
    freezed_annotation: ^3.1.0
    riverpod_annotation: ^4.0.0
    flutter_screenutil: ^5.9.3
    pigeon: ^26.1.7
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    connectivity_plus: ^7.0.0
    auto_size_text: ^3.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    flutter_launcher_icons: ^0.14.4
    freezed: ^3.2.3
    build_runner: ^2.10.5
    json_serializable: ^6.11.2
    riverpod_generator: ^4.0.0+1

flutter_intl:
    enabled: true
    class_name: Applang
    arb_dir: lib/core/lang/l10n
    output_dir: lib/core/lang/generated
    main_locale: es

flutter:
    uses-material-design: true

    # assets:
    #     - assets/images
    #     - assets/icons
